import { Suspense } from "React";

import type { Metadata } from "next";

import { Roboto } from "next/font/google";

import "./globals.css";

import AppFooter from '@/app/components/AppFooter';
import HockeyThemeProvider from '@/app/components/HockeyThemeProvider';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <HockeyThemeProvider>
          <Suspense>
          {children}
          </Suspense>
        </HockeyThemeProvider>
        <AppFooter />
      </body>
    </html>
  );
}
